# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff4dca8f07d74a0015d8018bbb486ccb6cf821241b512b6e802e1682308af086a10b519dea0d3caf2d1be018a7e10a3caab27200773d8586e5de4e1d842fc572

test:
  secret_key_base: 29c4fb979c0570cd0b272c25c3db65104fa35cef9872474f11c604a01b278324a25223f0619a17f49db3eb6a0a453276d905d89dffaca20f92b2a219fb2fa9a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
